### ISSUE TITLE
Create a "clone" for a new group at BCH

### ISSUE THREAD

**Issue by rudolphpienaar** [FNNDSC/fnndsc.babymri.org#2]
# New cloned site

Create delayedpuberty.fnndsc.org as a clone of the fnndsc site.

**Comment by rudolphpienaar** [comment]
gmail user: delayed.puberty.research
passwd: delayedpuberty123

**Comment by NicolasRannou** [comment]
@rudolphpienaar small note, it will be:
delayedpuberty.babymri.org

also, fnndsc domain is available if we want.

**Comment by NicolasRannou** [comment]
it is up and running at:
http://delayedpuberty.babymri.org/#welcome/home

**Comment by NicolasRannou** [comment]
we now we just need to know which chapters/pages and colors they want! All the pages to this website are hooked up to theirs gdrive already. Only images are being fetched from fnndsc's gdrive.

**Comment by rudolphpienaar** [comment]
great!
